name: Build ExpressLRS
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.target }}

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        pip install wheel

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio

    - name: Run PlatformIO Tests
      run: |
        platformio platform install native
        platformio platform update
        cd src
        PLATFORMIO_BUILD_FLAGS="-DRegulatory_Domain_ISM_2400" pio test -e native

  validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Validate target files
      run: |
        cd src
        python python/targets_validator.py

  targets:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-targets.outputs.targets }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: set-targets
      run: echo "::set-output name=targets::[$(grep -r "\[env:" src/targets | sed 's/.*://' | sed s/.$// | egrep "(STLINK|UART)" | grep -v DEPRECATED | tr '\n' ','  | sed 's/,$/"\n/' | sed 's/,/","/'g | sed 's/^/"/')]"

  build:
    needs: targets
    strategy:
      fail-fast: false
      matrix:
        target: ${{fromJSON(needs.targets.outputs.targets)}}
    runs-on: ubuntu-latest
    steps:

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.target }}

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        pip install wheel

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-platformio

    - name: Run PlatformIO
      run: |
        platformio platform update
        platformio platform install native
        mkdir -p ~/artifacts
        cd src
        case ${{matrix.target}} in
          *2400* | FM30*)
            export REG=-DRegulatory_Domain_ISM_2400
            ;;
          *)
            export REG=-DRegulatory_Domain_AU_915
            ;;
        esac
        # All the features
        PLATFORMIO_BUILD_FLAGS="$REG -DUSE_DIVERSITY -DDEBUG_LOG" pio run -e ${{ matrix.target }}
        # Minimal/default features
        PLATFORMIO_BUILD_FLAGS="$REG" pio run -e ${{ matrix.target }}
        mv .pio/build ~/artifacts/AU_915

    - name: Store Artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: ExpressLRS-${{ env.GITHUB_REF_SLUG_URL }}-${{ github.run_number }}
        path: ~/artifacts/**/*.bin
      continue-on-error: true
<<<<<<< HEAD

  firmware:
    needs: [build, validation, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get firmware artifacts
        uses: actions/download-artifact@v3
        with:
          name: firmware
          path: dist

      - name: Copy hardware files to firmware folder
        run: cp -r src/hardware dist/firmware

      - name: Copy bootloader files to firmware folder
        run: cd src ; find bootloader -name \*.bin -o -name \*.frk | grep -v src/ | cpio -pdm ../dist/firmware

      - name: Update firmware artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: dist/**/*

  installer:
    needs: [validation, test]
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - run: pip install pyserial
      - run: pip install pyinstaller
      - run: pyinstaller -F src/python/binary_configurator.py -n installer-${{ matrix.os }}

      - uses: actions/upload-artifact@v2
        with:
          name: installer
          path: dist/*
=======
>>>>>>> parent of 4fb6474b (Merge branch 'master' of https://github.com/SunjunKim/ExpressLRS)
